version: "3.7"
services:
  db:
    image: postgres:14
    container_name: marquez-db
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - MARQUEZ_DB=marquez
      - MARQUEZ_USER=marquez
      - MARQUEZ_PASSWORD=marquez
    volumes:
      - ./docker/init-db.sh:/docker-entrypoint-initdb.d/init-db.sh
    networks:
      - network_test
    healthcheck:
      test: >
        CMD sh -c '
        curl -s http://localhost:5001/healthcheck |
        jq -e ".postgresql.healthy == true" > /dev/null
        '
      interval: 30s
      timeout: 10s
      retries: 3
networks:
  network_test:
    name: network_test
    external: true
