version: "3.7"
services:
  api:
    depends_on:
      - db
      - opensearch
    entrypoint: ["/opt/marquez/wait-for-it.sh", "db:${POSTGRES_PORT}", "--", "/opt/marquez/wait-for-it.sh", "opensearch:${SEARCH_PORT}", "--", "./entrypoint.sh"]

  opensearch:
    image: opensearchproject/opensearch:2.5.0
    container_name: marquez-search
    hostname: opensearch
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    environment:
      - cluster.name=opensearch-cluster
      - node.name=opensearch
      - discovery.seed_hosts=opensearch
      - cluster.initial_cluster_manager_nodes=opensearch
      - bootstrap.memory_lock=true
      - plugins.security.ssl.http.enabled=false
      - "OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m"
      - OPENSEARCH_PASSWORD=admin
    volumes:
      - opensearch-data:/usr/share/opensearch/data
    cap_add:
      - IPC_LOCK
    ports:
      - "9200:9200"
      - "9300:9300"
    networks:
      - network_test
    healthcheck:
      test: >
        CMD sh -c '
        curl -s http://localhost:5001/healthcheck |
        jq -e ".deadlocks.healthy == true and .postgresql.healthy == true" > /dev/null
        '
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  opensearch-data:

networks:
  network_test:
    name: network_test
    external: true
